### ISSUE TITLE
Icon displaying in Navigation bar for all sites.

### ISSUE THREAD

**Issue by streetwolf** [wildskyf/TextareaCache#37] opened 2017-10-31 19:15 UTC
I am running the latest Fx58 inbound release.  I don't know if this is happening on Nightly yet.  I do have the pref to show the icon on the Nav bar disabled.  Whatever patch is causing this probably landed in the past couple of hours.  If it is a bad patch it might get backed out.  It could also be intentional.  I'll keep an eye on it as I routinely install the current inbound.

**Comment by wildskyf** [comment] 2017-11-18 13:53
Hi @streetwolf,

the problem is you want it to hide, but it still appears, right?
If yes, I will check my code and see whether there is any problem.

Or your issue is 'want an option to show icon on all sites'?
If yes, I will add it to the options page for you. :)

**Comment by wildskyf** [comment] 2017-11-20 06:31
page action will show on every page after v2.14.0
and it will hide if you cancel the checkbox in options page
so let's close this issue, if you still have any question, feel free to reopen it. :)

**Closed by wildskyf** 2017-11-20 06:31 UTC
Labels: discussing
