### ISSUE TITLE
URl bar icon again

### ISSUE THREAD

**Issue by rayman89** [wildskyf/TextareaCache#55] opened 2017-11-30 15:30 UTC
Seems that the icon is not appearing and showing as disabled on the "..." menu on some sites like mail.com and facebook among others.

**Comment by wildskyf** [comment] 2017-12-03 07:52
Thanks for your report, it will be fixed in the next version. :)

**Comment by wildskyf** [comment] 2017-12-03 10:34
ok, it should be fixed in the v3.4.1
If the problem is still there, feel free to reopen this issue.

**Closed by wildskyf** 2017-12-03 10:34 UTC
Labels: bug
